### PR TITLE
Update course previews edit flows and add preview banner

### PR DESCRIPTION
**Pull request by simonwhatley**

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Update course preview](https://trello.com/c/zEaHzf3s/1140-update-course-preview)

**Review by Kateharries — APPROVED** [review]
Looks good. We just need to update the banner body copy to: This is a preview of how your course will be displayed to candidates on Find postgraduate teacher training.

**Review by victoriawinlow — APPROVED** [review]
Nice wording Kate :)

**Comment by Kateharries** [comment]
> Nice wording Kate :)
Thanks - it looked a bit too long in the prototype so I just shortened a little.

**Pull request merged**
