### PR TITLE
Change GCSE equivalency questions

### PR DESCRIPTION
**Pull request by frankieroberto**
Reverting back to something closer to [the original design](https://bat-design-history.netlify.app/publish-teacher-training-courses/minimum-course-requirements-logic).

### CODE REVIEW

**Comment by frankieroberto** [comment]
Work in progress:

screenshot-localhost_3000-2021 05 20-15_34_04

**Comment by frankieroberto** [comment]
Slightly tweaked: 
gcses-wip

**Comment by paulrobertlloyd** [comment]
Looks good to me. Outstanding question is whether it’s give or accept equivalencies (or – gah – maybe both?). But we can prompt for that in the next round of UR.

Also, should the title be ‘Pending GCSEs and equivalency tests’?

**Comment by frankieroberto** [comment]
> Looks good to me. Outstanding question is whether it’s give or accept equivalencies (or – gah – maybe both?). But we can prompt for that in the next round of UR.

Yeah, I'm sure on that too. So far it seems that equivalency tests are nearly always something the providers have to offer, rather than something candidates may already have which can be accepted.

The main question currently says "Will you accept candidates who need to take an equivalency test in English, maths or science?", even though the follow-up question is "Which subjects can you offer equivalency tests in?", which is possibly confusing, but it does make the question consistent with "Will you accept candidates with pending GCSEs?", and maybe it makes sense to first ask about whether you'll accept those applications, and then which subjects you'll offer tests for?

One to keep an eye on though!

> Also, should the title be ‘Pending GCSEs and equivalency tests’?

I tried this, but it makes the title quite a bit longer, and the repetition of "pending" felt unnecessary (given that it also appears on the next line).

One option though is to just move each question onto its own page, which the [original design](https://bat-design-history.netlify.app/publish-teacher-training-courses/minimum-course-requirements-logic) does. We could come back to that idea after the testing.

**Pull request merged**
