### PR TITLE
Update organisation contact details

### PR DESCRIPTION
**Pull request by simonwhatley**

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Update organisation contact address form](https://trello.com/c/Qa0LmWlI/1271-update-organisation-contact-address-form)

**Review by Kateharries — APPROVED** [review]
This all looks good to me

**Comment by simonwhatley** [comment]
> Just curious, is there a reason why some parts of the page span half and the other bits span the full width

Where there is long-form content, the summary list spans the entire width to make it easier to read the information.

Where the content is short, the summary list is the normal two-thirds width to ensure the content is not too separated.

**Review by victoriawinlow — COMMENTED** [review]
All looks good

**Pull request merged**
