### PR TITLE
Update organisation details

### PR DESCRIPTION
**Pull request by simonwhatley**

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Update organisation details form](https://trello.com/c/kIJkZ6bl/1273-update-organisation-details-form)

**Review by Kateharries — COMMENTED** [review]
Looking at the error messages again, they look pretty long. I think we can use the acronym as they would have already read it written in full once they get to the field to enter the number. Also, I'm wondering if the provider doesn't have an AP ID we allow them to enter one. Once entered, it can't be changed (they would have to contact support if they make a mistake in entering it).

**Comment by simonwhatley** [comment]
@Kateharries, the error messages match the form field label, so whilst using the full name and not the acronym might be repetitive, it is _correct_. The error message at the field level should also correspond to the message in the error summary, where we must spell out the acronym.

From a support perspective, we allow the provider name and the accredited provider ID to be edited. I wonder if we should also allow it in Publish given we don't have a permissions model. It is probably risky to allow editing provider name, since it is reflected in Find, but less so accredited provider ID.

**Review by victoriawinlow — COMMENTED** [review]
Happy with this but re the comments, I think we should leave the editing of an AP ID to Support so it can be checked against the master list from Market Regs and then if that data is used downstream, it is accurate.

**Pull request merged**
